config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  devise_for :users

  resources :questions do
    get 'mark_best', on: :member
    resources :answers, only: [:new, :edit, :destroy, :create, :update]
  end

  resources :comments, except: [:index, :show]

  post 'new_vote', to: 'votes#new'

  get 'recent_questions', to: 'questions#recent'
  get 'popular_questions', to: 'questions#popular'
  get 'trending_questions', to: 'questions#trending'
  get 'user_profile', to: 'users#show'

end

app/models/question.rb
class Question < ActiveRecord::Base
  include Votable 
  
  belongs_to :user, inverse_of: :questions
  has_many :votes, as: :votable, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true
  validates :user, presence: true

  def get_answers
    best = [Answer.find_by(id: get_best_answer_id)].compact
    best | self.answers_by_vote
  end

  def get_best_answer_id
    if id = self.answers.find_by(is_best: true)
      id
    else
      0
    end
  end

  def mark_best(answer_id)
    self.answers.update_all(is_best: false)
    Answer.find_by(id: answer_id).update(is_best: true)
  end

  def answers_by_vote
    self.answers.sort_by {|a| a.net_vote}.reverse
  end

  def self.sort_by_popularity
    self.all.sort_by{ |q| q.net_vote }.reverse
  end

  def self.sort_by_trending
    self.all.sort_by{ |q| 
      q.count_recent_votes + q.count_recent_answers + q.count_recent_comments
    }.reverse[0..4]
  end


  def count_recent_votes
    Vote.where(created_at: 1.week.ago..Time.now, votable_type: "Question", votable_id: self.id).count
  end

  def count_recent_comments
    count = 0
    Answer.all.each do |a|
      if a.question_id == self.id
        a.comments.each do |c|
          if a.created_at >= Time.now
            count+=1
          end
        end 
      end
    end
    Comment.where(created_at: 1.week.ago..Time.now, commentable_type: "Question", commentable_id: self.id).count + count
  end

  def count_recent_answers
    Answer.where(created_at: 1.week.ago..Time.now, question_id: self.id).count
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show, :recent, :popular, :trending]
  before_action :set_question, only: [:show, :edit, :update, :destroy, :mark_best]

  def index
    @questions = Question.order created_at: :desc
  end

  def show
    unless @question
      redirect_to questions_path, alert: "That question does not seem to exist"
    end
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params.merge(user: current_user))
    if @question.save
      redirect_to question_path(@question)
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if (@question.user_id == current_user.id)
      if @question && @question.update(question_params)
        redirect_to question_path(@question)
      else
        render "edit"
      end
    else
      redirect_to questions_path, alert: "That was bad, and you should feel bad.  You're bad."
    end
  end

  def destroy
    if (@question.user_id == current_user.id)
      @question.destroy
      redirect_to questions_path
    else
      redirect_to questions_path, alert: "That was bad, and you should feel bad.  You're bad."
    end
  end

  def mark_best
    @question.mark_best(params[:answer_id])
    redirect_to question_path(@question)
  end

  def recent
    redirect_to questions_path
  end

  def popular
    @questions = Question.sort_by_popularity
    render 'index'
  end

  def trending
    @questions = Question.sort_by_trending
    render 'index'
  end

  protected

  def set_question
    @question = Question.find_by(id: params[:id])
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, :user_id)
  end
end

app/views/questions/_form.html.erb
<div class='form-container'>
  <div class='form-header'>
    <h2>Here is the form title!</h2>
  </div>

  <div class='form-body'>
	  <%= form_for @question do |f| %>
	    <p>Here is a description regarding the form.</p>

	    <ul>
				<% @question.errors.full_messages.each do |e| %>
					<li><%= e %></li>
				<% end %>
			</ul>

      <ul>
        <li>
          <%= f.label :title %>
          <%= f.text_field :title %>
        </li>
        <li>
          <%= f.label :body %>
					<%= f.text_area :body %>
        </li>
      </ul>

      <%= f.submit %>
  	<% end %>
  </div>
</div>

app/views/questions/edit.html.erb
<%= render "form" %>
<%= button_to "Delete", question_path(@question), method: :delete %>

app/views/questions/index.html.erb
<div class='question-all-container'>
  <div class='question-header'>
    <h2>View Questions</h2>
    <div class='question-header-links'>
      <%= link_to "Ask a question!", new_question_path %>
      <ul>
        <li>Sort by:</li>
        <li><%= link_to 'Recent', recent_questions_path %></li>
        <li><%= link_to 'Popular', popular_questions_path %></li>
        <li><%= link_to 'Trending', trending_questions_path %></li>
      </ul>
    </div>
  </div>

  <% @questions.each do |question| %>
    <div class='question'>
      <div class='question-header'>
        <h4><%= link_to question.title, question_path(question) %></h4>
        <span class='question-votes'><%= question.net_vote %></span>
      </div>
      <div class='question-content'>
        <p>User: <%= question.user.email %></p>
        <p><%= question.created_at.strftime(" Asked on %m/%d/%Y at %I:%M%p") %></p>
        <%= question.count_recent_votes %> total votes,
        <%= question.count_recent_answers %> answers,
        <%= question.count_recent_comments %> comments
      </div>
    </div>
  <% end %>
</div>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/questions/show.html.erb
<div class='question-show-container'>
  <div class='question-show-question'>
    <div class='question-show-question-header'>
      <h1><%= @question.title %></h1>
      <p>Question asked by <%= @question.user.email %> at <%= @question.created_at.strftime("%m/%d/%Y, %I:%M%p") %>.</p>
      <% if @question.user == current_user %>
        <p>This is yours! Would you like to <%= link_to 'edit your question', edit_question_path(@question) %>?</p>
      <% end %>
    </div>
    <div class='question-show-question-body'>
      <p><%= @question.body %></p>
      <div class='question-show-votes-container'>
        <%= render partial: 'shared/question_votes', layout: false, locals: { question: @question} %>
      </div>
    </div>
    <div class='question-show-question-footer'>
      <p><%= link_to 'Add Answer', new_question_answer_path(@question) %></p>
      <p><%= link_to 'Add Comment', new_comment_path(commentable_type: 'Question', commentable_id: @question.id) %></p>
    </div>
    <div class='question-show-comments'>
      <%= render partial: "shared/comments", locals: { comments: @question.comments } %>
    </div>
  </div>
  <div class='question-show-answers'>
    <div class='question-show-answers-header'>
      <h2>Answers</h2>
    </div>
    <div class='question-show-answers-container'>
      <%= render partial: "shared/answers", locals: { answers: @question.get_answers } %>
    </div>
  </div>
</div>