config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  devise_for :users

  resources :questions do
    get 'mark_best', on: :member
    resources :answers, only: [:new, :edit, :destroy, :create, :update]
  end

  resources :comments, except: [:index, :show]

  post 'new_vote', to: 'votes#new'

  get 'recent_questions', to: 'questions#recent'
  get 'popular_questions', to: 'questions#popular'
  get 'trending_questions', to: 'questions#trending'
  get 'user_profile', to: 'users#show'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def get_recent_questions(id)
    questions = Question.where(user_id: id)
    questions.sort_by{ |q| q.created_at }.reverse
  end

  def get_recent_answers(id)
    answers = Answer.where(user: id)
    answers.sort_by{ |a| a.created_at }.reverse
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
    render 'show'
  end
end

app/views/users/show.html.erb
Welcome to your profile, <%= @user.email %>!

<p><%= link_to "Edit your stuff!", edit_user_registration_path %></p>

<p>Here is your recent actvitity:</p>

<p>Questions:</p>
<ul>
  <% @user.get_recent_questions(@user.id).each do |q| %>
    <li><%= link_to q.title, question_path(q) %></li>
  <% end %>
</ul>

<p>Answers:</p>
<ul>
  <% @user.get_recent_answers(@user.id).each do |a| %>
    <li>
      <p><%= link_to "In response to: " + a.question.title, question_path(a.question) %></p>
      <%= a.body %>
    </li>
  <% end %>
</ul>