config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  devise_for :users

  resources :questions do
    get 'mark_best', on: :member
    resources :answers, only: [:new, :edit, :destroy, :create, :update]
  end

  resources :comments, except: [:index, :show]

  post 'new_vote', to: 'votes#new'

  get 'recent_questions', to: 'questions#recent'
  get 'popular_questions', to: 'questions#popular'
  get 'trending_questions', to: 'questions#trending'
  get 'user_profile', to: 'users#show'

end

app/views/shared/_answer_votes.html.erb
<div class='question-show-votes <%= answer.vote_class(current_user) %>'>
  <%= link_to "/\\", new_vote_path(votable_type: 'Answer', votable_id: answer.id, value: 1, question_id: question.id) %>
  <%= answer.net_vote %>
  <%= link_to '\/', new_vote_path(votable_type: 'Answer', votable_id: answer.id, value: -1, question_id: question.id) %>
</div>

app/views/shared/_answers.html.erb
<% answers.each do |answer| %>
  <div class='question-show-answer<%= " best-answer" if answer.is_best %>'>
    <% if answer.is_best %>
    <div class='best-answer-box'>
      <p>This answer was voted best by the question asker!</p>
    </div>
    <% end %>
    <div class='question-show-answer-body'>
      <p>By <%= answer.user.email %> at <%= answer.created_at.strftime("on %m/%d/%Y at %I:%M%p") %>:</p>
      <div class='question-show-votes-container'>
        <%= render partial: 'shared/answer_votes', layout: false, locals: { question: @question, answer: answer} %>
      </div>
      <p><%= answer.body %></p>
    </div>
    <div class='question-show-answer-footer'>
      <p class='question-show-answer-add-comment'><%= link_to 'Add Comment', new_comment_path(commentable_type: 'Answer', commentable_id: answer.id) %></p>
      <% if answer.user == current_user %>
        <p class='question-show-answer-add-comment'><%= link_to 'Edit Your Answer!', edit_question_answer_path(@question, answer) %></p>
      <% end %>
      <% if @question.user == current_user %>
        <p class='question-show-answer-add-comment'><%= link_to 'Mark This Best!', mark_best_question_path(@question, answer_id: answer.id, ), id: @question.id %></p>
      <% end %>
    </div>
    <div class='question-show-comments'>  
      <%= render partial: "shared/comments", locals: { comments: answer.comments } %>
    </div>
  </div>
<% end %>

app/views/shared/_comment_single.html.erb
<div class='comment'>
  <span class='question-show-votes-container'>
    <%= render partial: 'shared/comment_votes', layout: false, locals: { question: question, comment: comment } %>
  </span>
  <p><%= comment.body %></p>
</div>

app/views/shared/_comment_votes.html.erb
<p class='<%= comment.vote_class(current_user) %>'><%= comment.net_vote.to_s + " #{comment.net_vote == 1 ? 'point' : 'points'}" %>, <%= comment.user.email %> at <%= comment.created_at.strftime("%m/%d/%Y %I:%M %p") %> (<%= link_to "Vote Up", new_vote_path(votable_type: 'Comment', votable_id: comment.id, value: 1, question_id: question.id) %> or <%= link_to "Vote Down", new_vote_path(votable_type: 'Comment', votable_id: comment.id, value: -1, question_id: question.id) %>) <% if comment.user == current_user %><%= link_to "Delete", comment_path(comment), method: :delete %><% end %></p>

app/views/shared/_comments.html.erb
<% comments.each do |comment| %>
  <div class='comment'>
    <span class='question-show-votes-container'>
      <%= render partial: 'shared/comment_votes', layout: false, locals: { question: @question, comment: comment } %>
    </span>
    <p><%= comment.body %></p>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <h2><%= link_to "Stack Awesomeflow", "https://github.com/secade/Stack-Awesomeflow" %> developed by:</h2>
  <ul>
    <li><%= link_to "Chris", "https://github.com/secade" %></li>
    <li><%= link_to "Maisam", "https://github.com/Maisam" %></li>
    <li><%= link_to "Mary", "https://github.com/MaryCBaylis" %></li>
    <li><%= link_to "Peter", "https://github.com/felix-starman" %></li>
  </ul>
</footer>

app/views/shared/_header.html.erb
<nav>
  <h1><%= link_to "Stack Awesomeflow", root_path %></h1>
  <ul>
    <% if user_signed_in? %>
      <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
      <li><%= link_to "My Profile", user_profile_path %></li>
    <% else %>
      <li><%= link_to "Register", new_user_registration_path %></li>
      <li><%= link_to "Login", new_user_session_path %></li>
    <% end %>
  </ul>
</nav>

app/views/shared/_question_votes.html.erb
<div class='question-show-votes <%= question.vote_class(current_user) %>'>
  <%= link_to "/\\", new_vote_path(votable_type: 'Question', votable_id: question.id, value: 1, question_id: question.id) %>
  <span class='vote-text'><%= question.net_vote %></span>
  <%= link_to '\/', new_vote_path(votable_type: 'Question', votable_id: question.id, value: -1, question_id: question.id) %>
</div>