config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  devise_for :users

  resources :questions do
    get 'mark_best', on: :member
    resources :answers, only: [:new, :edit, :destroy, :create, :update]
  end

  resources :comments, except: [:index, :show]

  post 'new_vote', to: 'votes#new'

  get 'recent_questions', to: 'questions#recent'
  get 'popular_questions', to: 'questions#popular'
  get 'trending_questions', to: 'questions#trending'
  get 'user_profile', to: 'users#show'

end

app/models/answer.rb
require 'votable'

class Answer < ActiveRecord::Base
  include Votable
  
  belongs_to :user, inverse_of: :answers
  belongs_to :question, inverse_of: :answers
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :votes, as: :votable, dependent: :destroy

  validates :body, presence: true
  validates :user, presence: true
  validates :question, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :set_question
  before_action :set_answer, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def new
    @answer = Answer.new
  end

  def create
    user = User.find_by(id: current_user.id)
    @answer = Answer.new(question: @question, body: params[:answer][:body], user: user)
    if (@answer.save)
      redirect_to question_path(@question)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @answer.user_id == current_user.id
      if @answer.update(body: params[:answer][:body])
        redirect_to question_path(@question)
      else
        render 'edit'
      end
    else
      redirect_to questions_path, alert: "That was bad, and you should feel bad.  You're bad."
    end
  end

  def destroy
    if @answer.user_id == current_user.id
      @answer.destroy
      redirect_to questions_path, alert: "You successfully deleted your answer."
    else
      redirect_to questions_path, alert: "That was bad, and you should feel bad.  You're bad."
    end
  end

  protected

  def set_question
    @question = Question.find_by(id: params[:question_id])
  end

  def set_answer
    @answer = Answer.find_by(id: params[:id])
  end

  private

  def answer_params
    params.require[:answer].permit(:body)
  end

end

app/views/answers/_form.html.erb
<div class='form-container'>
  <div class='form-header'>
    <h2>Add an Answer</h2>
  </div>

<div class='form-body'>
    <%= form_for [@question, @answer] do |f| %>
      <p>Enter your comment below.</p>
      <% if @answer.errors.any? %>
        <ul>
          <% @answer.errors.full_messages.each do |e| %>
            <li><%= e %></li>
          <% end %>
        </ul>
      <% end %>

      <ul>
        <li>
          <%= f.label :body %>
          <%= f.text_area :body %>
        </li>
      </ul>

      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/answers/edit.html.erb
<%= render "form" %>
<%= button_to "Delete", question_answer_path(@question, @answer), method: :delete %>

app/views/answers/new.html.erb
<%= render 'form' %>